### ISSUE TITLE
Ponyfill?

### ISSUE THREAD

**Issue by tomek-he-him** [stefanduberg/array-find#1]
Looks like you’ve modelled the API after the ES6 [`Array.find`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/array/find). How about using `Array.find` when it’s available?

Here’s what a _ponyfill_ is: https://github.com/medikoo/es6-weak-map/issues/7#issue-73596863.

**Comment by stefanduberg** [comment]
Thank you for your suggestion.

Like this? https://github.com/stefanduberg/array-find/blob/88d83a94dd529d6312d27414f7ac6339154c9ed4/find.js#L4-L6

**Comment by tomek-he-him** [comment]
:+1: Brilliant! :)

**Comment by tomek-he-him** [comment]
@stefanduberg could release this great update to npm please?

**Comment by stefanduberg** [comment]
Released to npm now!

**Comment by tomek-he-him** [comment]
:+1: :+1:
